name: Tests

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    name: Build and Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ghc: ['9.6.7']
        cabal: ['3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache cabal store
      uses: actions/cache@v4
      with:
        path: |
          ~/.cabal/store
          ~/.cabal/packages
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('**/*.cabal', '**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-cabal-

    - name: Update cabal package list
      run: cabal update

    - name: Build project
      run: cabal build exe:brainfuchs

    - name: Run tests
      run: cabal test --test-show-details=direct

